name: Build Jar

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Set Time
        run: echo "time=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: carpet-lunaar-addons-${{ env.time }}.jar
          path: |
            build/libs/carpet-lunaar-addons*.jar
            !build/libs/*sources.jar
            !build/libs/*dev.jar
